Automatically set 'offset' parameter if 'messages' parameter is set
mlc-ai/mlc-llm pull request #754
Opened 2023-08-14 18:01 UTC by sbelcmu

This change will automatically set the `offset` parameter if the `messages` parameter is set while still allowing the user to override the offset if necessary.

2023-08-14 22:16 UTC, sbelcmu commented
I am not too familiar with the C++ side, could anyone take a look and let me know if there is anything else that needs to be done?

2023-08-15 00:32 UTC, tqchen approved these changes

2023-08-15 00:32 UTC, tqchen commented on cpp/conversation.cc
>      CHECK(partial_update) << "Key \"offset\" not found.";
this check should be removed

2023-08-15 00:32 UTC, tqchen requested changes
note, cc @yzh119 for cross check

2023-08-16 04:51 UTC, tqchen approved these changes

2023-08-16 04:51 UTC, merged